/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-2',
  aws_appsync_graphqlEndpoint:
    'https://nbilkquogvef3jorclbodlbw3m.appsync-api.us-east-2.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-2',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-sryx6a4unvd57it76xt454pjbu',
  aws_cognito_identity_pool_id:
    'us-east-2:53fb0c04-c3de-4d03-867b-ce649b9c3a97',
  aws_cognito_region: 'us-east-2',
  aws_user_pools_id: 'us-east-2_3V9BXpjpv',
  aws_user_pools_web_client_id: '3vgu0o7o2t5joukisfua2thonh',
  oauth: {},
  aws_cognito_username_attributes: ['EMAIL'],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ['EMAIL', 'PREFERRED_USERNAME', 'PICTURE'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [
      'REQUIRES_LOWERCASE',
      'REQUIRES_NUMBERS',
      'REQUIRES_SYMBOLS',
      'REQUIRES_UPPERCASE',
    ],
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
}

export default awsmobile
